### PR TITLE
Issue 22/delete people information

### PR DESCRIPTION
**Pull request by developerPratik**
added route for deleting people; 
added button and styling for deleting people

### CODE REVIEW

**Comment by sumn2u** [comment]
@developerPratik  Follows things are needed to accept your pull request.

- Image is not deleted from images 
- Values are not deleted from people page

**Comment by developerPratik** [comment]
okay @sumn2u dai, will incorporate those changes as well

**Comment by rabishah** [comment]
👍

**Comment by sumn2u** [comment]
:+1:  :fireworks:  :trophy:  Kudos! first merge ! @developerPratik  thank you for your work.

**Pull request closed without merging**
